"""Cohort calendar, generated by formula. Nothing is imported.

One cohort starts on the 1st of every month and runs 3 months, ending on the last
day of its third month. Cohort 25 starts 2026-10-01; count back one month per cohort.
"""
import argparse
import calendar

import config
from common import connect


def add_months(year, month, delta):
    idx = year * 12 + (month - 1) + delta
    return idx // 12, idx % 12 + 1


def cohort_dates(n):
    ay, am = config.COHORT_ANCHOR_START
    sy, sm = add_months(ay, am, -(config.COHORT_ANCHOR_NUMBER - n))
    ey, em = add_months(sy, sm, 2)
    last_day = calendar.monthrange(ey, em)[1]
    return f"{sy:04d}-{sm:02d}-01", f"{ey:04d}-{em:02d}-{last_day:02d}"


def cohort_rows(through):
    rows = []
    for n in range(1, through + 1):
        start, end = cohort_dates(n)
        tracked = 0 if n <= config.COHORT_UNTRACKED_THROUGH else 1
        note = "predates tracking" if not tracked else None
        rows.append((n, start, end, tracked, note))
    return rows


def load_cohorts(conn, through=25):
    rows = cohort_rows(through)
    conn.executemany(
        "INSERT INTO cohorts(cohort_number,start_date,end_date,tracked,note) VALUES (?,?,?,?,?)"
        " ON CONFLICT(cohort_number) DO UPDATE SET start_date=excluded.start_date,"
        " end_date=excluded.end_date, tracked=excluded.tracked, note=excluded.note",
        rows,
    )
    conn.commit()
    return rows


def main():
    ap = argparse.ArgumentParser(description="Generate the cohort calendar.")
    ap.add_argument("--through", type=int, default=25, help="highest cohort number to generate (default 25)")
    args = ap.parse_args()
    conn = connect()
    try:
        rows = load_cohorts(conn, args.through)
    finally:
        conn.close()
    print(f"{'Cohort':>6}  {'Start':<10}  {'End':<10}  Tracked  Note")
    for n, start, end, tracked, note in rows:
        print(f"{n:>6}  {start:<10}  {end:<10}  {tracked:^7}  {note or ''}")
    print(f"\n{len(rows)} cohorts written.")


if __name__ == "__main__":
    main()
